name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate:
    uses: mirenchaps/ci-platform/.github/workflows/gitops-validate.yml@main
    with:
      prometheus-rule-paths: |
        argocd/rules